NIE_3V2/CSE/urls.py

from django.urls import path
from CSE import views
from CSE.views import StuList, Forms, StudentDetail, StudentUpdate, StudentDelete

app_name = 'CSE'

urlpatterns = [
    path('index', views.index, name='home'),
    path('index', views.index, name='index'),
    path('products', views.products, name='products'),
    path('service', views.service, name='service'),
    path('contacts', views.contacts, name='contacts'),
    path('basic', views.basic, name='basic'),

    # CBV
    path('', StuList.as_view(), name='list'),
    path('forms', Forms.as_view(), name='forms'),
    path('<pk>/detail', StudentDetail.as_view(), name='detail'),
    path('<pk>/update', StudentUpdate.as_view(), name='update'),
    path('<pk>/delete', StudentDelete.as_view(), name='delete'),

    # FBV
    path('student', views.student, name='student'),  # Only keep one
    path('form', views.form, name='form'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

    ###GET and POST

    path('nie',views.nie, name = 'nie'),
    path('add', views.add, name = 'add'),
    path('add1', views.add1, name = 'add1'),

    # login, logout, user registration
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login'),
    path('logout', views.logoutuser, name = 'logout'),

]

NIE_3V2/NIE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CSE.urls')),
]

NIE_3V2/CSE/models.py
from django.db import models

# Create your models here.

class employee(models.Model):
    emp_name = models.CharField(max_length=50)
    emp_number = models.IntegerField()
    def __str__(self):
        return self.emp_name
class Student(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=30)
    college_name = models.CharField(max_length=30)
    rollnumber = models.IntegerField()
    def __str__(self):
        return self.name

NIE_3V2/CSE/forms.py
# for FBV

from django.forms import ModelForm

from .models import Student

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"


# for login, logout, user registrration
from django import forms
from django.forms import ModelForm 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

NIE_3V2/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html', context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')


def basic(request):
    return render(request,'basic.html')

# FBV

from django.shortcuts import render, redirect, get_object_or_404

from CSE.models import Student
from CSE.forms import StudentForm

#Create view

def form(request):
    
    form = StudentForm
    if request.method =="POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('CSE:student')  

    context = {'form': form}
    return render(request, 'FBV/form.html', context) 



#list view
def student(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request,'FBV/student.html',context)

#detail view
def detail(request, id):
	data = Student.objects.get(id = id)	
	context = {'data':data}
	return render(request,'FBV/detail.html', context)

#Update view
def update(request, id):
	obj = get_object_or_404(Student, id =id) 
	form = StudentForm(request.POST or None, instance = obj)
	data = Student.objects.get(id = id)
	if form.is_valid():
		form.save()
		return redirect('CSE:student')

	context = {'form':form, 'data':data}
	return render(request,'FBV/update.html', context )

#delete view

def delete(request, id):
	data = Student.objects.get(id = id)
	context = {'data':data}
	if request.method =='POST':
		data.delete()
		return redirect('CSE:student')
	return render(request,'FBV/delete.html', context )














# CBV

from CSE.models import Student ,employee
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = employee
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = employee
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = employee
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = employee
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'


class StudentDelete(DeleteView):
    model = employee
    template_name = 'CBV/delete.html'
    success_url = '/'



# GET and POST
def nie(request):
	return render(request,'nie.html')


def add(request):
	a = int(request.GET['num1'])
	b = int(request.GET['num2'])
	c = a+b
	context = {'result':c}
	return render(request, 'add.html', context)

def add1(request):
	a = int(request.POST['num1'])
	b = int(request.POST['num2'])
	c = a+b
	context = {'result':c}
	return render(request, 'add.html', context)


# for login, logout, user registration

from django.shortcuts import render, redirect
from .forms import CreateUserForm 

from django.contrib.auth import login
from django.contrib import messages

# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
#from django.contrib import authenticate, login, logout
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required 



@login_required(login_url = 'login')
def home(request):
	return render (request,"home.html", context = {})





def register(request):
	
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Your Account has been created for '+ user)
			return redirect('CSE:login')


	context = { 'form': form }
	return render (request, 'Login/register.html', context)


def login_reg(request):

	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username = username, password = password)
		if user is not None:
			login(request, user)
			return redirect('CSE:home')
		else:
			messages.info(request, "Username Or password is incorrect.")


	context = {}
	return render (request, 'Login/login.html', context)

def logoutuser(request):
	logout(request)
	return redirect('CSE:login')


NIE_3V2/templates/CBV/delete.html

{% extends 'basic.html' %}

{% block content %}
<h1>Employee Delete page.</h1>
<form method="post">
    {% csrf_token %} <br><br><br>
    <h1>    Are you sure you want to delete "{{ object }}"? </h1>
      <br><br><br><br>

    <table class="table table-striped table-bordered table-hover table-condensed">
    <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <!-- <th scope="col">Department</th> -->
            <th scope="col">Employee number</th>
            <!-- <th scope="col">College Name</th> -->
            <th scope="col">ID</th>
            
          </tr>
        </thead>
        <tbody>
           
          <tr>
            
            <td>{{object.emp_name}}</td>
            <!-- <td>{{object.department}}</td> -->
            <!-- <td>{{object.college_name}}</td> -->
            <td>{{object.emp_number}}</td>
            <td>{{object.id}}</td>
                
            
           
          </tr>
         
        </tbody>
    </table>
    </table>
    <input type="submit" class = " btn btn-danger" style = "border-radius: 20px;" value="Confirm">
    <a type = "button" class="btn btn-success " href="{% url 'CSE:list' %}" style = "border-radius: 20px;">No</a>
    
</form>

{% endblock %}


NIE_3V2/templates/CBV/detail.html

{% extends 'basic.html' %}

{% block content %}
<h1>Employee detail page.</h1>

<table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <!-- <th scope="col">Department</th> -->
        <!-- <th scope="col">Roll.number</th> -->
        <!-- <th scope="col">College Name</th> -->
        <th scope="col">Employee number</th>
        
      </tr>
    </thead>
    <tbody>
       
      <tr>
        
        <td>{{object.emp_name}}</td>
        <!-- <td>{{object.department}}</td>
        <td>{{object.rollnumber}}</td> -->
        <td>{{object.emp_number}}</td>
        <!-- <td>{{object.id}}</td> -->
        
      </tr>
     
    </tbody>
  </table>

{% endblock %}


NIE_3V2/templates/CBV/forms.html

{% extends 'basic.html' %}

{% block content %}
<h1>Employee Application form page.</h1>

<form action  = '', method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value = "Submit" class = "btn btn-success" style = "border-radius: 20px;"><br><br><br><br><br><br>
    
</form> 

{% endblock %}


NIE_3V2/templates/CBV/list.html

{% extends 'basic.html' %}

{% block content %}

<h1>Employee List page.</h1><br>
<table>
    <tr>
        <th>ID</th>
        <th>Employee Name</th>
        <!-- <th>Department</th> -->
        <!-- <th>Year</th> -->
        <th>Employee id</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>
        
        
    </tr>
    {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>{{object.emp_name}}</td>
                <!-- <td> {{object.department}}</td> -->
                <!-- <td>{{object.college_name}}</td> -->
                <td> {{object.emp_number}} </td>  
                <td><a type="button" class="btn btn-primary" style="border-radius: 20px;" href= "{{object.id}}/detail">Detail</a></td>
                <td><a type=" button " class = "btn btn-success" style="border-radius: 20px;" href ="{{object.id}}/update" >Update</a></td>
                <td><a type = "button" class="btn btn-danger" style="border-radius: 20px;" href="{{object.id}}/delete">Delete</a></td>
                                      
            </tr>
            
    {% endfor %}

</table>

{% endblock %}

NIE_3V2/templates/CBV/update.html

{% extends 'basic.html' %}

{% block content %}
<h1>Employee Update page.</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class = "button" value="Save">   
    
</form>


{% endblock %}


NIE_3V2/templates/FBV/delete.html
{% extends 'basic.html' %}

{% block content %}

<div class="main">
    <!-- Create a Form -->
<form method="POST">
        <!-- Security token by Django -->
    {% csrf_token %}

<h4>    Are you want to delete this item ?</h4><br>


        <h1>{{ data.name }}</h1>
        <br>
            <input type="submit" value="Yes, Delete" />
           
            <a href = "{% url "CSE:student" %}">Cancel</a>
            
   
</form>
</div>


{% endblock %}

NIE_3V2/templates/FBV/detail.html
{% extends 'basic.html' %}

{% block content %}

<h1>Student Details page</h1>

Index.No : {{ data.id }}<br>
Name: {{data.name}}<br>
Department: {{data.department}}<br>
College Name: {{data.college_name}}<br>
Roll Number: {{data.rollnumber}}<br><br>


{% endblock %}

NIE_3V2/templates/FBV/form.html
{% extends 'basic.html' %}

{% block content %}


<div>
    <form action = "" method = "post">
        {% csrf_token %}
        {{form.as_p }}
        <input type="submit" value= "Submit">
    </form>
</div>


{% endblock %}

NIE_3V2/templates/FBV/student.html

{% extends 'basic.html' %}

{% block content %}
<h1>This is a student page.</h1>

<ul>
    {% for student in students %}
    <li>Index value:{{student.id}}</li>
    <li>Name :{{student.name}}</li>
    <li>Department :{{student.department}}</li>
    <li>College name :{{student.college_name}}</li>
    <li>Roll number :{{student.rollnumber}}</li> 
    <a type="button" class="btn btn-primary" style="border-radius: 20px;" href= "detail/{{student.id}}">Detail</a>
    <a type=" button " class = "btn btn-success" style="border-radius: 20px;" href ="update/{{student.id}}" >Update</a>
    <a type = "button" class="btn btn-danger" style="border-radius: 20px;" href="delete/{{student.id}}">Delete</a>
    <hr>
    {% endfor %}
</ul>

{% endblock %}

NIE_3V2/templates/FBV/update.html
{%extends 'basic.html' %}

 {% block content %}
 
 <div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}

    <h4>    Do you want to Update this item ? </h4><br>
<div>
     <table style="width:100%"; border-spacing: 5px;>

              <tr>
                <th>Roll.No</th>
                <th >Name</th>
                <th >Department</th>
                <th >Phone number</th>
                <th >Address</th>
                
              </tr>
                    
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.name }}</td>
                <td>{{ data.department }}</td>
                <td>{{ data.contact }}</td>
                <td>{{ data.address }}</td>
                

            </tr>
        
    </table> <br><br>
    <div>
		<h1>Enter the values to be updated here.</h1>
    			{{ form.as_p }}
    </div>

        <input type="submit" value="Yes, Update" />
        <a href="/">Cancel </a>
    </form>
</div>


 
 
 {% endblock %} 

NIE_3V2/templates/Login/login.html
{% extends 'basic.html' %}

{% block content %}

<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


  <style>
    body,
    html {
      margin: 0;
      padding: 0;
      height: 100%;
      background: #7abecc !important;
    }
    .user_card {
      width: 350px;
      margin-top: auto;
      margin-bottom: auto;
      background: #74cfbf;
      position: relative;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding: 10px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 5px;

    }

    .form_container {
      margin-top: 20px;
    }

    #form-title{
      color: #fff;
      
    }

    .login_btn {
      width: 100%;
      background: #33ccff !important;
      color: white !important;
    }
    .login_btn:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }
    .login_container {
      padding: 0 2rem;
    }
    .input-group-text {
      background: #f7ba5b !important;
      color: white !important;
      border: 0 !important;
      border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }

    #messages{
      background-color: grey;
      color: #fff;
      padding: 10px;
      margin-top: 10px;
    }
  </style>

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">


          <h3 id="form-title">LOGIN</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="login_reg">
            {% csrf_token %}
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
                <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login">
                </div>
          </form>

        </div>
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'CSE:register' %}" class="ml-2">Sign Up</a>
          </div>
      
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock%}

</html>

NIE_3V2/templates/Login/register.html
{% extends 'basic.html' %}

{% block content %}

<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  <style>
    body,
    html {
      margin: 0;
      padding: 0;
      height: 100%;
      background: #7abecc !important;
    }
    .user_card {
      width: 350px;
      margin-top: auto;
      margin-bottom: auto;
      background: #74cfbf;
      position: relative;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding: 10px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      border-radius: 5px;

    }

    .form_container {
      margin-top: 20px;
    }

    #form-title{
      color: #fff;
    }
    .login_btn {
      width: 100%;
      background: #33ccff !important;
      color: white !important;
    }
    .login_btn:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }
    .login_container {
      padding: 0 2rem;
    }
    .input-group-text {
      background: #f7ba5b !important;
      color: white !important;
      border: 0 !important;
      border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
      box-shadow: none !important;
      outline: 0px !important;
    }

  </style>

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <h3 id="form-title">REGISTER ACCOUNT</h3>
        </div>
        <div class="d-flex justify-content-center form_container">

          <form method="POST" action="">
            {% csrf_token %}
      
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              {{ form.username }}
            </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
              </div>
              {{ form.email }}
              </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
              {{ form.password1 }}
              </div>
            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
              {{ form.password2 }}
              
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
              <input class="btn login_btn" type="submit" value="Register Account">
              </div>
          </form>
        </div>
    

    {{ form.errors }}
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Already have an account? <a href="{% url 'CSE:login' %}" class="ml-2">Login</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
            /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field 
     */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){ 
      form_fields[field].className += ' form-control'
    }
  </script>
</body>
{% endblock%}
</html>

<!---

<h1>Register</h1>

<form method  = 'POST' action = 'register'>
  <h1>CreateUserForm</h1>
      {% csrf_token %}
      {{ form.username.label }}
      {{ form.username }}

{{ form.email.label }}
      {{ form.email }}
{{ form.password1.label }}
      {{ form.password1 }}
{{ form.password2.label }} ---------1
      {{ form.password2 }}

--->


<!---
          {%  for field in form %}
             {{ field.label }}  -----------2
             {{ field }}
             <br>
             
          {% endfor %}
--->

<!---
  <input type="submit" name="Create User">
  <br><hr>
</form>   ---------------1


--->

NIE_3V2/templates/add.html
{% extends 'basic.html' %}

{% block content %}

<h1>Result is : {{ result }} </h1>

{% endblock %}

NIE_3V2/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django_web development</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'CSE:index' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'CSE:index' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:products' %}">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:service' %}">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:contacts' %}">Contacts</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:student' %}">FBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:list' %}">CBV-Student</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'CSE:forms' %}">Student Apply</a>
              </li>

              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  FBV_Student
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'CSE:student' %}">FBV-List</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:form' %}">FBV-regiration</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:nie' %}">GET-POST Addision of two numbers</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:register' %}">User - Registration </a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:login' %}">login </a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:logout' %}">logout </a></li>
                </ul>
              </div>

              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  CBV_Student
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'CSE:list' %}">CBV-List</a></li>
                  <li><a class="dropdown-item" href="{% url 'CSE:forms' %}">CBV-regiration</a></li>
                 
                </ul>
              </div>
              <div>
                {% if user.is_authenticated %}
                      <p>Welcome, {{ user.username }}!</p>
                {% else %}
                      <p>Welcome, Guest!</p>
                {% endif %}

              </div>
              
                          
          </div>
        </div>
      </nav>


    </nav> 

    {% block content %}

    {% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

NIE_3V2/templates/contacts.html
{% extends 'basic.html' %}


{% block content %}
<h1> This is a contacts page.</h1>

{% endblock %}

NIE_3V2/templates/index.html
{% extends 'basic.html' %}

{% block content %}
<h1>Welcome to web development</h1>

{% endblock %}

NIE_3V2/templates/nie.html
{% extends 'basic.html' %}

{% block content %}
<h1>We are discussing about GET and POST requests.</h1>

GET request:
<form action = 'add'>
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>
</form>

POST request:

<form action = 'add1' method = 'post'>
    {% csrf_token %}
    Enter the first number:<input type = 'text' name='num1'><br><br>
    Enter the second number:<input type = 'text' name='num2'><br><br>
    <input type = 'submit'>
</form>

{% endblock %}

NIE_3V2/templates/products.html
{% extends 'basic.html' %}

{% block content %}
<h1>This is a products page.</h1>
Name: {{name}}<br>
Department: {{d_name}}<br>
College:{{c_name}}<br>
Roll number: {{r_number}}
{% endblock %}








This is a products page.

NIE_3V2/templates/service.html

{% extends 'basic.html' %}

{% block content %}
<h1>This is a service page.</h1>

{% endblock %}